$cores = 1
$mem = 512

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-14.04-i386-1"
  config.vm.hostname = "refbox"

  config.vm.provider "kvm" do |v|
    v.memory_size = '%dm' % $mem
    v.core_number = $cores
  end
  config.vm.provider "virtualbox" do |v|
    config.vm.synced_folder './', '/vagrant', type: '9p', readonly: true
    v.memory = $mem
    v.cpus = $cores
  end

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.ssh.insert_key = true

  config.vm.provision "shell", path: "../scripts/common/lockdown.sh"
end
