$cores = 1
$mem = 512

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-14.04-amd64-1"
  config.vm.hostname = "refbox"

  config.vm.provider "libvirt" do |v|
    v.memory = $mem
    v.cpus = $cores
  end
  config.vm.provider "virtualbox" do |v|
    v.memory = $mem
    v.cpus = $cores
  end

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.ssh.insert_key = true

  config.vm.provision "shell", path: "../scripts/common/lockdown.sh"
end
