Vagrant.configure("2") do |config|
  # Configure the box
  config.vm.box = "ubuntu-14.04-i386-1"
  config.vm.hostname = "refbox"

  # Configure SSH access
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.ssh.insert_key = true

  # Do some basic provisioning
  config.vm.provision "shell", path: "../scripts/common/lockdown.sh"
end
