#!/bin/bash
if [[ $# != 2 ]]; then
  echo >&2 "Usage: $0 target provider"
  exit 1
fi
tmpdr=`mktemp -d /tmp/build.XXXXXXXX`
fname=$tmpdr/template.json
USER=`whoami`
PUBKEY=`cat ~/.ssh/id_rsa.pub`
TIMEZONE=Europe/Berlin
which python2 && PY=python2 || PY=python
$PY create_template.py target=$1 provider=$2 \
    user_name=$USER \
    "user_pubkey=$PUBKEY" \
    "time_zone=$TIMEZONE" \
      > $fname || (rm $fname; exit 1)
echo "Using template at $fname"
packer build $fname && rm $fname
