# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Configure the box
  config.vm.box = "freebsd-10.1-amd64"
  config.vm.hostname = "bsdbox"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Configure SSH access
  config.ssh.username = "vagrant"

  # Do some basic provisioning
  config.vm.provision "shell", path: "../scripts/common/vim.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/common/zsh.sh", privileged: false

end
