Vagrant.configure("2") do |config|
  # Configure the box
  config.vm.box = "ubuntu-14.04-i386-qemu"
  config.vm.hostname = "websrv"

  # Configure SSH access
  config.ssh.username = "niklas"
  config.ssh.private_key_path = "~/.ssh/id_rsa"

  # Forward guest:80 to host:8000
  config.vm.network "forwarded_port", guest: 80, host: 8000

  # Share the webroot to the VM
  # Warning: Wait until apache is configured before
  # copying stuff to ./webroot
  config.vm.synced_folder "webroot", "/var/www/html"

  # VirtualBox customization
  config.vm.provider "kvm" do |p|
    p.memory_size = "1GiB"
  end

  # Do some basic provisioning
  config.vm.provision "shell", path: "../scripts/ubuntu/websrv.sh"

end
