# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Configure the box
  config.vm.box = "ubuntu-14.10-amd64"
  config.vm.hostname = "websrv"

  # Configure SSH access
  config.ssh.username = "sam"
  config.ssh.private_key_path = "~/.ssh/id_rsa"

  # Forward guest:80 to host:8000
  config.vm.network "forwarded_port", guest: 80, host: 8000

  # Share the webroot to the VM
  # Warning: Wait until apache is configured before
  # copying stuff to ./webroot
  config.vm.synced_folder "webroot", "/var/www/html"

  # VirtualBox customization
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  # Do some basic provisioning
  config.vm.provision "shell", path: "../scripts/ubuntu/websrv.sh"
  config.vm.provision "shell", path: "../scripts/debian/lockdown.sh"

end
